# Generated by Django 4.2.7 on 2023-11-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_data_name_alter_data_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
