# Generated by Django 4.2.5 on 2023-11-10 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupancy', models.PositiveIntegerField(choices=[(0, 'Commercial'), (1, 'Residential'), (2, 'Industrial')], null=True)),
                ('floors', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('roofing', models.PositiveIntegerField(choices=[(0, 'No leaks'), (1, 'Leaks')], null=True)),
                ('seismic_zone', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('cracks', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('l_arrestors', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('anti_eathquake', models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('soil_type', models.PositiveIntegerField(choices=[(0, 'No leaks'), (1, 'Leaks')], null=True)),
                ('wall_thickness', models.PositiveIntegerField(choices=[(0, 'Thin'), (1, 'Thick')], null=True)),
                ('predictions', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
