# Generated by Django 4.2.5 on 2023-11-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
